### ISSUE TITLE
Run Cypress in Github actions

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/writer#10]
https://github.com/cypress-io/github-action

**Comment by gearsdigital** [comment]
I added the _cypress github action_ recently to my Kirby 3 Plugin "Enhanced Toolbar Link Dialog" (gearsdigital/enhanced-toolbar-link-dialog/pull/28). 

I can take care when nobody is working on it.

**Comment by bastianallgeier** [comment]
@gearsdigital That would be amazing!!

**Comment by gearsdigital** [comment]
Sure thing!

**Comment by gearsdigital** [comment]
@bastianallgeier I opened a PR which should fit your needs. Let me know if i've missed something...
